import React, { useRef } from 'react'
import ItemCard from './ItemCard'
import CardBack from './CardBack'

export default function SharePanel({ item }) {
  const printRef = useRef()

  if (!item) return null

  const handlePrint = () => {
    window.print()
  }

  const handleShare = async () => {
    const shareText = formatShareText(item)

    if (navigator.share) {
      try {
        await navigator.share({
          title: `HeroQuest Loot: ${item.name}`,
          text: shareText,
        })
      } catch {
        // User cancelled — ignore
      }
    } else {
      // Fallback: copy to clipboard
      await navigator.clipboard.writeText(shareText)
      alert('Item copied to clipboard!')
    }
  }

  const btnStyle = {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 20px',
    borderRadius: 6,
    border: '1px solid #5a3a0a',
    background: '#2a1400',
    color: '#c9a227',
    fontFamily: '"Crimson Text", Georgia, serif',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  }

  return (
    <>
      {/* Action buttons — hidden when printing */}
      <div
        className="no-print"
        style={{ display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'center', marginTop: 24 }}
      >
        <button style={btnStyle} onClick={handlePrint}>
          🖨️ Print / Save PDF
        </button>
        <button style={btnStyle} onClick={handleShare}>
          📤 Share
        </button>
      </div>

      {/* Print layout — only visible when printing */}
      <div
        ref={printRef}
        style={{ display: 'none' }}
        className="print-only"
      >
        <PrintLayout item={item} />
      </div>

      <style>{`
        @media print {
          body > * { display: none !important; }
          .print-layout-root { display: flex !important; }
        }
      `}</style>
    </>
  )
}

function PrintLayout({ item }) {
  return (
    <div className="print-layout-root" style={{
      display: 'none',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 40,
    }}>
      {/* Front side */}
      <div style={{ pageBreakAfter: 'always', display: 'flex', justifyContent: 'center', padding: 40 }}>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
          <p style={{ fontFamily: '"Cinzel", serif', fontSize: 12, color: '#999', margin: '0 0 8px' }}>
            FRONT — CUT ALONG EDGE
          </p>
          <ItemCard item={item} />
        </div>
      </div>

      {/* Back side — on new page */}
      <div style={{ pageBreakBefore: 'always', display: 'flex', justifyContent: 'center', padding: 40 }}>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
          <p style={{ fontFamily: '"Cinzel", serif', fontSize: 12, color: '#999', margin: '0 0 8px' }}>
            BACK — FOLD AND GLUE OR SLEEVE
          </p>
          <CardBack tier={item.tier} />
        </div>
      </div>
    </div>
  )
}

function formatShareText(item) {
  const tierName = { 1: 'Legendary Artifact', 2: 'Ancient Relic', 3: 'Enchanted Item', 4: 'Treasure Card' }[item.tier] || `Tier ${item.tier}`
  const atk = item.attackDice > 0 ? `Attack: ${item.attackDice} combat dice | ` : ''
  const def = item.defenseDice > 0 ? `Defense: ${item.defenseDice} combat dice | ` : ''
  const restrict = item.heroRestriction === 'Any' ? 'All Heroes' : `${item.heroRestriction} Only`

  return [
    `⚔ ${item.name}`,
    `${tierName} — ${item.slot}`,
    '',
    `${atk}${def}${restrict}`,
    '',
    item.effect,
    '',
    `"${item.flavorText}"`,
    '',
    '🎲 Generated by HeroQuest Loot Generator',
  ].join('\n')
}
